#!/usr/bin/env bash

# Copyright 2021 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

REPO_ROOT=$(git rev-parse --show-toplevel);
KOPSPATH=$REPO_ROOT/.build/dist/$(go env GOOS)/$(go env GOARCH)
PATH=$KOPSPATH:$PATH

KUBETEST2_COMMON_ARGS="-v=2 --cloud-provider=scaleway --cluster-name=e2e-test-scw.k8s.local --kops-binary-path=${KOPSPATH}/kops"
KUBETEST2_COMMON_ARGS="${KUBETEST2_COMMON_ARGS} --admin-access=${ADMIN_ACCESS:-}"

export GO111MODULE=on
go get sigs.k8s.io/kubetest2/...@latest

make gomod

cd ${REPO_ROOT}/tests/e2e
#
#echo "*** go mod tidy"
#go mod tidy
#echo "OKAY !"
##
#echo "*** go mod vendor"
#go mod vendor
#echo "OKAY !"
##
echo "*** installing kubetest2-kops"
go install ./kubetest2-kops
##go install -mod=readonly ./kubetest2-kops
echo "*** OKAY !"
#
echo "*** installing kubetest2-tester-kops"
go install ./kubetest2-tester-kops
echo "*** OKAY !"

#echo "*** FIRST COMMAND ***"
#kubetest2 kops ${KUBETEST2_COMMON_ARGS} --build --kops-root=${REPO_ROOT} --stage-location=${STAGE_LOCATION:-}
#echo "*** OKAY !"

echo "*** SECOND COMMAND ***"
kubetest2 kops ${KUBETEST2_COMMON_ARGS} \
		-v 6 \
		--up --down \
		--env S3_ENDPOINT=https://s3.fr-par.scw.cloud \
		--env JOB_NAME=pull-kops-e2e-kubernetes-scw-kubetest2 \
		--create-args "--networking=cilium --api-loadbalancer-type=public --node-count=2 --master-count=3" \
		--kops-version-marker=https://storage.googleapis.com/k8s-staging-kops/kops/releases/markers/release-1.20/latest-ci.txt \
		--kubernetes-version=https://storage.googleapis.com/kubernetes-release/release/stable-1.20.txt \
		--test=kops \
		-- \
		--ginkgo-args="--debug" \
		--test-package-marker=stable-1.20.txt \
		--parallel 25
#		--skip-regex="\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler|nfs|NFS|Services.*functioning.*NodePort|Services.*rejected.*endpoints|Services.*NodePort.*listening.*same.*port|TCP.CLOSE_WAIT|should.*run.*through.*the.*lifecycle.*of.*Pods.*and.*PodStatus"
echo "*** OKAY !"
