# To regenerate the manifest:
#   cd upup/models/cloudup/resources/addons/hcloud-csi-driver.addons.k8s.io
#   ./regenerate.sh

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: hcloud-csi
    repo: https://charts.hetzner.cloud
    version: "2.22.2"
    releaseName: hcloud-csi
    namespace: kube-system
    valuesFile: helm-values.yaml
