version: "2"
run:
  go: "1.25"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - usetesting
  settings:
    staticcheck:
      checks:
        - all
        - -SA1019
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - ineffassign
        path: conversion\\.go
      - linters:
          - errcheck
          - funlen
          - goconst
          - gocyclo
          - gosec
        path: _test\\.go
      - path: (.+)\.go$
        text: zz_generated.*\.go$
      - path: (.+)\.go$
        text: third_party/
      - path: (.+)\.go$
        text: builtin/
      - path: (.+)\.go$
        text: examples/
      - path: (.+)\.go$
        text: vendor/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - k8s.io/kops
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
