# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1800s
options:
  substitution_option: ALLOW_LOOSE
  machineType: "E2_HIGHCPU_32"
steps:
  # Build & Push the images
  - name: "mirror.gcr.io/library/golang:1.25.7-trixie"
    id: images
    entrypoint: make
    env:
      - CI=$_CI
      - DOCKER_IMAGE_REGISTRY=$_DOCKER_IMAGE_REGISTRY
    args:
      - kops-utils-cp-push
      - kops-controller-push
      - dns-controller-push
      - kube-apiserver-healthcheck-push
      - discovery-server-push
  # Build & push the binaries
  - name: "mirror.gcr.io/library/golang:1.25.7-trixie"
    id: binaries
    entrypoint: make
    env:
      # _GIT_TAG is not a valid semver, we use CI=1 instead
      # - VERSION=$_GIT_TAG
      - CI=$_CI
      - GCS_BUCKET=$_GCS_BUCKET
    args:
      - gcs-upload-and-tag
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _CI: "1"
  _GIT_TAG: "12345"
  _PULL_BASE_REF: "dev"
  _DOCKER_IMAGE_REGISTRY: "gcr.io/k8s-staging-kops"
  _GCS_BUCKET: "gs://k8s-staging-kops"
