apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2025-05-14T15:52:44Z"
  name: test.k8s
spec:
  cloudProvider: elemento
  kubelet:
    cloudProvider: external
    anonymousAuth: false
  api:
    loadBalancer:
      type: Public
  controlPlaneKubelet:
    cloudProvider: external
    anonymousAuth: false
  api:
    loadBalancer:
      type: Public 