#!/bin/bash

# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

# start at the root of the repo
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}"

# Go through all our modules and update them to the latest version
# We exclude a few dependencies
# IDEA: Can we create a tool that will make this easier?  Make like a .upgrade-deps.yaml or .codebots.yaml file in each module?

cd "${REPO_ROOT}"
go get $(go list -f '{{if not (or .Main .Indirect)}}{{.Path}}{{end}}' -mod=mod -m all | grep -v spotinst-sdk-go)

cd "${REPO_ROOT}/hack"
go get $(go list -f '{{if not (or .Main .Indirect)}}{{.Path}}{{end}}' -mod=mod -m all)

cd "${REPO_ROOT}/tests/e2e"
go get $(go list -f '{{if not (or .Main .Indirect)}}{{.Path}}{{end}}' -mod=mod -m all | grep -v kubetest2)

cd "${REPO_ROOT}/tools/otel/traceserver"
go get $(go list -f '{{if not (or .Main .Indirect)}}{{.Path}}{{end}}' -mod=mod -m all)

# Tidy go modules
cd "${REPO_ROOT}"
make gomod

if $(git diff --quiet); then
  echo "No changes"
else
  git add .
  git commit -m "codebot: update-dependencies"
  echo "Updated dependencies"
fi
