# To regenerate the manifest:
#   cd upup/models/cloudup/resources/addons/azuredisk-csi-driver.addons.k8s.io
#   ./regenerate.sh

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: azuredisk-csi-driver
    repo: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
    version: "1.34.4"
    releaseName: azuredisk-csi-driver
    namespace: kube-system
    valuesFile: helm-values.yaml
