#!/usr/bin/env bash

# Copyright 2024 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

REPO_ROOT=$(git rev-parse --show-toplevel)
cd ${REPO_ROOT}

systemctl disable --user qemu-vm0 || true
systemctl disable --user qemu-vm1 || true
systemctl disable --user qemu-vm2 || true
systemctl disable --user qemu-dhcp || true
systemctl disable --user qemu-storage || true

systemctl stop --user qemu-vm0 || true
systemctl stop --user qemu-vm1 || true
systemctl stop --user qemu-vm2 || true
systemctl stop --user qemu-dhcp || true
systemctl stop --user qemu-storage || true

sudo ip link del dev tap-vm0 || true
sudo ip link del dev tap-vm1 || true
sudo ip link del dev tap-vm2 || true

rm -rf .build/vm0
rm -rf .build/vm1
rm -rf .build/vm2

