#!/usr/bin/env bash

# Copyright 2024 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

REPO_ROOT=$(git rev-parse --show-toplevel)
cd ${REPO_ROOT}

ip route || true

ip link || true

ip addr || true

sudo iptables --list-rules || true
sudo iptables -t nat --list-rules || true


journalctl --no-pager --user -xeu qemu-dhcp.service || true
journalctl --no-pager --user -xeu qemu-storage.service || true
journalctl --no-pager --user -xeu qemu-vm0.service || true
journalctl --no-pager --user -xeu qemu-vm1.service || true
journalctl --no-pager --user -xeu qemu-vm2.service || true
