#!/usr/bin/env bash

# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export KOPS_FEATURE_FLAGS=
export DNSCONTROLLER_IMAGE=
export KOPS_STATE_STORE=
export S3_REGION=
export S3_ACCESS_KEY_ID=
export S3_SECRET_ACCESS_KEY=
export S3_ENDPOINT=
export VSPHERE_USERNAME=
export VSPHERE_PASSWORD=
export TARGET=
export TARGET_PATH=
export NODEUP_URL=
export PROTOKUBE_IMAGE=

echo "KOPS_FEATURE_FLAGS=${KOPS_FEATURE_FLAGS}"
echo "DNSCONTROLLER_IMAGE=${DNSCONTROLLER_IMAGE}"
echo "KOPS_STATE_STORE=${KOPS_STATE_STORE}"
echo "S3_REGION=${S3_REGION}"
echo "S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}"
echo "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}"
echo "S3_ENDPOINT=${S3_ENDPOINT}"
echo "VSPHERE_USERNAME=${VSPHERE_USERNAME}"
echo "VSPHERE_PASSWORD=${VSPHERE_PASSWORD}"
echo "NODEUP_URL=${NODEUP_URL}"
echo "PROTOKUBE_IMAGE=${PROTOKUBE_IMAGE}"
echo "TARGET=${TARGET}"
echo "TARGET_PATH=${TARGET_PATH}"
