/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	kopsv1alpha3 "k8s.io/kops/pkg/apis/kops/v1alpha3"
	scheme "k8s.io/kops/pkg/client/clientset_generated/clientset/scheme"
)

// SSHCredentialsGetter has a method to return a SSHCredentialInterface.
// A group's client should implement this interface.
type SSHCredentialsGetter interface {
	SSHCredentials(namespace string) SSHCredentialInterface
}

// SSHCredentialInterface has methods to work with SSHCredential resources.
type SSHCredentialInterface interface {
	Create(ctx context.Context, sSHCredential *kopsv1alpha3.SSHCredential, opts v1.CreateOptions) (*kopsv1alpha3.SSHCredential, error)
	Update(ctx context.Context, sSHCredential *kopsv1alpha3.SSHCredential, opts v1.UpdateOptions) (*kopsv1alpha3.SSHCredential, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kopsv1alpha3.SSHCredential, error)
	List(ctx context.Context, opts v1.ListOptions) (*kopsv1alpha3.SSHCredentialList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kopsv1alpha3.SSHCredential, err error)
	SSHCredentialExpansion
}

// sSHCredentials implements SSHCredentialInterface
type sSHCredentials struct {
	*gentype.ClientWithList[*kopsv1alpha3.SSHCredential, *kopsv1alpha3.SSHCredentialList]
}

// newSSHCredentials returns a SSHCredentials
func newSSHCredentials(c *KopsV1alpha3Client, namespace string) *sSHCredentials {
	return &sSHCredentials{
		gentype.NewClientWithList[*kopsv1alpha3.SSHCredential, *kopsv1alpha3.SSHCredentialList](
			"sshcredentials",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kopsv1alpha3.SSHCredential { return &kopsv1alpha3.SSHCredential{} },
			func() *kopsv1alpha3.SSHCredentialList { return &kopsv1alpha3.SSHCredentialList{} },
		),
	}
}
