#!/usr/bin/env bash

# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script generates go code for the proto definitions.

set -ex

go install ./vendor/github.com/golang/protobuf/protoc-gen-go

protoc --go_out=plugins=grpc:../.. pkg/proto/nodebootstrap/bootstrap.proto
rm -f pkg/proto/nodebootstrap/bootstrap.pb.go.tmp
mv pkg/proto/nodebootstrap/bootstrap.pb.go pkg/proto/nodebootstrap/bootstrap.pb.go.tmp
cat hack/boilerplate/boilerplate.generatego.txt pkg/proto/nodebootstrap/bootstrap.pb.go.tmp > pkg/proto/nodebootstrap/bootstrap.pb.go
rm -f pkg/proto/nodebootstrap/bootstrap.pb.go.tmp
