$testable_packages = Get-Content .\hack\.packages | select-string -notmatch "k8s.io/kops/cloudmock","k8s.io/kops/vendor"
go-bindata -o upup/models/bindata.go -pkg models -ignore="\\.DS_Store" -ignore="bindata\\.go" -ignore="vfs\\.go" -prefix upup/models/ upup/models/...
go-bindata -o federation/model/bindata.go -pkg model -ignore="\\.DS_Store" -ignore="bindata\\.go" -ignore="vfs\\.go" -prefix federation/model/ federation/model/...
go test -v $testable_packages