// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: pkg/testdata/testdata.proto

package testdata

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TestJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bucket string `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *TestJob) Reset() {
	*x = TestJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_testdata_testdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestJob) ProtoMessage() {}

func (x *TestJob) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_testdata_testdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestJob.ProtoReflect.Descriptor instead.
func (*TestJob) Descriptor() ([]byte, []int) {
	return file_pkg_testdata_testdata_proto_rawDescGZIP(), []int{0}
}

func (x *TestJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestJob) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *TestJob) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type TestJobRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	RunName string `protobuf:"bytes,2,opt,name=run_name,json=runName,proto3" json:"run_name,omitempty"`
	Bucket  string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix  string `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *TestJobRun) Reset() {
	*x = TestJobRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_testdata_testdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestJobRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestJobRun) ProtoMessage() {}

func (x *TestJobRun) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_testdata_testdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestJobRun.ProtoReflect.Descriptor instead.
func (*TestJobRun) Descriptor() ([]byte, []int) {
	return file_pkg_testdata_testdata_proto_rawDescGZIP(), []int{1}
}

func (x *TestJobRun) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *TestJobRun) GetRunName() string {
	if x != nil {
		return x.RunName
	}
	return ""
}

func (x *TestJobRun) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *TestJobRun) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type TestJobRunResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName   string            `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	RunName   string            `protobuf:"bytes,2,opt,name=run_name,json=runName,proto3" json:"run_name,omitempty"`
	Result    string            `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Timestamp uint64            `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Passed    bool              `protobuf:"varint,5,opt,name=passed,proto3" json:"passed,omitempty"`
	Features  []*TestJobFeature `protobuf:"bytes,6,rep,name=features,proto3" json:"features,omitempty"`
}

func (x *TestJobRunResults) Reset() {
	*x = TestJobRunResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_testdata_testdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestJobRunResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestJobRunResults) ProtoMessage() {}

func (x *TestJobRunResults) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_testdata_testdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestJobRunResults.ProtoReflect.Descriptor instead.
func (*TestJobRunResults) Descriptor() ([]byte, []int) {
	return file_pkg_testdata_testdata_proto_rawDescGZIP(), []int{2}
}

func (x *TestJobRunResults) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *TestJobRunResults) GetRunName() string {
	if x != nil {
		return x.RunName
	}
	return ""
}

func (x *TestJobRunResults) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TestJobRunResults) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TestJobRunResults) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *TestJobRunResults) GetFeatures() []*TestJobFeature {
	if x != nil {
		return x.Features
	}
	return nil
}

type TestJobFeature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TestJobFeature) Reset() {
	*x = TestJobFeature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_testdata_testdata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestJobFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestJobFeature) ProtoMessage() {}

func (x *TestJobFeature) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_testdata_testdata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestJobFeature.ProtoReflect.Descriptor instead.
func (*TestJobFeature) Descriptor() ([]byte, []int) {
	return file_pkg_testdata_testdata_proto_rawDescGZIP(), []int{3}
}

func (x *TestJobFeature) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TestJobFeature) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListTestJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTestJobsRequest) Reset() {
	*x = ListTestJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_testdata_testdata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTestJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestJobsRequest) ProtoMessage() {}

func (x *ListTestJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_testdata_testdata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestJobsRequest.ProtoReflect.Descriptor instead.
func (*ListTestJobsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_testdata_testdata_proto_rawDescGZIP(), []int{4}
}

type ListTestJobRunsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job *TestJob `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *ListTestJobRunsRequest) Reset() {
	*x = ListTestJobRunsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_testdata_testdata_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTestJobRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestJobRunsRequest) ProtoMessage() {}

func (x *ListTestJobRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_testdata_testdata_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestJobRunsRequest.ProtoReflect.Descriptor instead.
func (*ListTestJobRunsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_testdata_testdata_proto_rawDescGZIP(), []int{5}
}

func (x *ListTestJobRunsRequest) GetJob() *TestJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetTestJobRunResultsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Run *TestJobRun `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
}

func (x *GetTestJobRunResultsRequest) Reset() {
	*x = GetTestJobRunResultsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_testdata_testdata_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestJobRunResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestJobRunResultsRequest) ProtoMessage() {}

func (x *GetTestJobRunResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_testdata_testdata_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestJobRunResultsRequest.ProtoReflect.Descriptor instead.
func (*GetTestJobRunResultsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_testdata_testdata_proto_rawDescGZIP(), []int{6}
}

func (x *GetTestJobRunResultsRequest) GetRun() *TestJobRun {
	if x != nil {
		return x.Run
	}
	return nil
}

var File_pkg_testdata_testdata_proto protoreflect.FileDescriptor

var file_pkg_testdata_testdata_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a,
	0x07, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0x72, 0x0a, 0x0a,
	0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f,
	0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f,
	0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x75, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x22, 0xc4, 0x01, 0x0a, 0x11, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x75, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x12, 0x2b, 0x0a, 0x08, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x08, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x4a,
	0x6f, 0x62, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x22, 0x3c,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x03, 0x72, 0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x65, 0x73,
	0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x52, 0x03, 0x72, 0x75, 0x6e, 0x32, 0xc7, 0x01, 0x0a,
	0x08, 0x54, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x0c, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x14, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x08, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3b, 0x0a,
	0x0f, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x73,
	0x12, 0x17, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x54, 0x65, 0x73, 0x74,
	0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4a, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_testdata_testdata_proto_rawDescOnce sync.Once
	file_pkg_testdata_testdata_proto_rawDescData = file_pkg_testdata_testdata_proto_rawDesc
)

func file_pkg_testdata_testdata_proto_rawDescGZIP() []byte {
	file_pkg_testdata_testdata_proto_rawDescOnce.Do(func() {
		file_pkg_testdata_testdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_testdata_testdata_proto_rawDescData)
	})
	return file_pkg_testdata_testdata_proto_rawDescData
}

var file_pkg_testdata_testdata_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_testdata_testdata_proto_goTypes = []interface{}{
	(*TestJob)(nil),                     // 0: TestJob
	(*TestJobRun)(nil),                  // 1: TestJobRun
	(*TestJobRunResults)(nil),           // 2: TestJobRunResults
	(*TestJobFeature)(nil),              // 3: TestJobFeature
	(*ListTestJobsRequest)(nil),         // 4: ListTestJobsRequest
	(*ListTestJobRunsRequest)(nil),      // 5: ListTestJobRunsRequest
	(*GetTestJobRunResultsRequest)(nil), // 6: GetTestJobRunResultsRequest
}
var file_pkg_testdata_testdata_proto_depIdxs = []int32{
	3, // 0: TestJobRunResults.features:type_name -> TestJobFeature
	0, // 1: ListTestJobRunsRequest.job:type_name -> TestJob
	1, // 2: GetTestJobRunResultsRequest.run:type_name -> TestJobRun
	4, // 3: TestData.ListTestJobs:input_type -> ListTestJobsRequest
	5, // 4: TestData.ListTestJobRuns:input_type -> ListTestJobRunsRequest
	6, // 5: TestData.GetTestJobRunResults:input_type -> GetTestJobRunResultsRequest
	0, // 6: TestData.ListTestJobs:output_type -> TestJob
	1, // 7: TestData.ListTestJobRuns:output_type -> TestJobRun
	2, // 8: TestData.GetTestJobRunResults:output_type -> TestJobRunResults
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_testdata_testdata_proto_init() }
func file_pkg_testdata_testdata_proto_init() {
	if File_pkg_testdata_testdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_testdata_testdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_testdata_testdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestJobRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_testdata_testdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestJobRunResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_testdata_testdata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestJobFeature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_testdata_testdata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTestJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_testdata_testdata_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTestJobRunsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_testdata_testdata_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestJobRunResultsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_testdata_testdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_testdata_testdata_proto_goTypes,
		DependencyIndexes: file_pkg_testdata_testdata_proto_depIdxs,
		MessageInfos:      file_pkg_testdata_testdata_proto_msgTypes,
	}.Build()
	File_pkg_testdata_testdata_proto = out.File
	file_pkg_testdata_testdata_proto_rawDesc = nil
	file_pkg_testdata_testdata_proto_goTypes = nil
	file_pkg_testdata_testdata_proto_depIdxs = nil
}
