#!/bin/bash

# Copyright 2015 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is intended to be run periodically, to check the health
# of docker.  If it detects a failure, it will restart docker using systemctl.

healthcheck() {
   if output=`timeout 60 docker network ls`; then
       echo "$output" | fgrep -qw host || {
          echo "Docker 'host' network missing"
          return 1
       }
   else
       echo "Docker returned $?"
       return 1
   fi
}

if healthcheck; then
  echo "Docker healthy"
  exit 0
fi

echo "Docker failed"
echo "Giving docker 30 seconds grace before restarting"
sleep 30

if healthcheck; then
  echo "docker recovered"
  exit 0
fi

echo "Docker still unresponsive; triggering docker restart"
systemctl stop docker

echo "Wait for all tcp sockets to close, `cat /proc/sys/net/ipv4/tcp_fin_timeout` seconds"
sleep `cat /proc/sys/net/ipv4/tcp_fin_timeout`

sleep 10
systemctl start docker

echo "Waiting for 120 seconds to give docker time to start"
sleep 120

if healthcheck; then
  echo "Docker recovered"
  exit 0
fi

echo "Docker still failing"
