// Code generated by ""fitask" -type=AutoscalingGroup"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// AutoscalingGroup

// JSON marshalling boilerplate
type realAutoscalingGroup AutoscalingGroup

func (o *AutoscalingGroup) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realAutoscalingGroup
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = AutoscalingGroup(r)
	return nil
}

var _ fi.HasName = &AutoscalingGroup{}

func (e *AutoscalingGroup) GetName() *string {
	return e.Name
}

func (e *AutoscalingGroup) SetName(name string) {
	e.Name = &name
}

func (e *AutoscalingGroup) String() string {
	return fi.TaskAsString(e)
}
