// Code generated by ""fitask" -type=DHCPOptions"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// DHCPOptions

// JSON marshalling boilerplate
type realDHCPOptions DHCPOptions

func (o *DHCPOptions) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realDHCPOptions
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = DHCPOptions(r)
	return nil
}

var _ fi.HasName = &DHCPOptions{}

func (e *DHCPOptions) GetName() *string {
	return e.Name
}

func (e *DHCPOptions) SetName(name string) {
	e.Name = &name
}

func (e *DHCPOptions) String() string {
	return fi.TaskAsString(e)
}
