// Code generated by ""fitask" -type=DHCPOptions"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// DHCPOptions

// JSON marshalling boilerplate
type realDHCPOptions DHCPOptions

// UnmarshalJSON implements conversion to JSON, supporitng an alternate specification of the object as a string
func (o *DHCPOptions) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realDHCPOptions
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = DHCPOptions(r)
	return nil
}

var _ fi.HasName = &DHCPOptions{}

// GetName returns the Name of the object, implementing fi.HasName
func (o *DHCPOptions) GetName() *string {
	return o.Name
}

// SetName sets the Name of the object, implementing fi.SetName
func (o *DHCPOptions) SetName(name string) {
	o.Name = &name
}

// String is the stringer function for the task, producing readable output using fi.TaskAsString
func (o *DHCPOptions) String() string {
	return fi.TaskAsString(o)
}
