// Code generated by ""fitask" -type=DNSName"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// DNSName

// JSON marshalling boilerplate
type realDNSName DNSName

func (o *DNSName) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realDNSName
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = DNSName(r)
	return nil
}

var _ fi.HasName = &DNSName{}

func (e *DNSName) GetName() *string {
	return e.Name
}

func (e *DNSName) SetName(name string) {
	e.Name = &name
}

func (e *DNSName) String() string {
	return fi.TaskAsString(e)
}
