// Code generated by ""fitask" -type=ElasticIP"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// ElasticIP

// JSON marshalling boilerplate
type realElasticIP ElasticIP

// UnmarshalJSON implements conversion to JSON, supporitng an alternate specification of the object as a string
func (o *ElasticIP) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realElasticIP
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = ElasticIP(r)
	return nil
}

var _ fi.HasName = &ElasticIP{}

// GetName returns the Name of the object, implementing fi.HasName
func (o *ElasticIP) GetName() *string {
	return o.Name
}

// SetName sets the Name of the object, implementing fi.SetName
func (o *ElasticIP) SetName(name string) {
	o.Name = &name
}

// String is the stringer function for the task, producing readable output using fi.TaskAsString
func (o *ElasticIP) String() string {
	return fi.TaskAsString(o)
}
