// Code generated by ""fitask" -type=IAMInstanceProfile"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// IAMInstanceProfile

// JSON marshalling boilerplate
type realIAMInstanceProfile IAMInstanceProfile

// UnmarshalJSON implements conversion to JSON, supporitng an alternate specification of the object as a string
func (o *IAMInstanceProfile) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realIAMInstanceProfile
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = IAMInstanceProfile(r)
	return nil
}

var _ fi.HasName = &IAMInstanceProfile{}

// GetName returns the Name of the object, implementing fi.HasName
func (o *IAMInstanceProfile) GetName() *string {
	return o.Name
}

// SetName sets the Name of the object, implementing fi.SetName
func (o *IAMInstanceProfile) SetName(name string) {
	o.Name = &name
}

// String is the stringer function for the task, producing readable output using fi.TaskAsString
func (o *IAMInstanceProfile) String() string {
	return fi.TaskAsString(o)
}
