// Code generated by ""fitask" -type=InternetGateway"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// InternetGateway

// JSON marshalling boilerplate
type realInternetGateway InternetGateway

func (o *InternetGateway) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realInternetGateway
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = InternetGateway(r)
	return nil
}

var _ fi.HasName = &InternetGateway{}

func (e *InternetGateway) GetName() *string {
	return e.Name
}

func (e *InternetGateway) SetName(name string) {
	e.Name = &name
}

func (e *InternetGateway) String() string {
	return fi.TaskAsString(e)
}
