// Code generated by ""fitask" -type=LoadBalancerHealthChecks"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// LoadBalancerHealthChecks

// JSON marshalling boilerplate
type realLoadBalancerHealthChecks LoadBalancerHealthChecks

func (o *LoadBalancerHealthChecks) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realLoadBalancerHealthChecks
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = LoadBalancerHealthChecks(r)
	return nil
}

var _ fi.HasName = &LoadBalancerHealthChecks{}

func (e *LoadBalancerHealthChecks) GetName() *string {
	return e.Name
}

func (e *LoadBalancerHealthChecks) SetName(name string) {
	e.Name = &name
}

func (e *LoadBalancerHealthChecks) String() string {
	return fi.TaskAsString(e)
}
