// Code generated by ""fitask" -type=RouteTableAssociation"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// RouteTableAssociation

// JSON marshalling boilerplate
type realRouteTableAssociation RouteTableAssociation

func (o *RouteTableAssociation) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realRouteTableAssociation
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = RouteTableAssociation(r)
	return nil
}

var _ fi.HasName = &RouteTableAssociation{}

func (e *RouteTableAssociation) GetName() *string {
	return e.Name
}

func (e *RouteTableAssociation) SetName(name string) {
	e.Name = &name
}

func (e *RouteTableAssociation) String() string {
	return fi.TaskAsString(e)
}
