// Code generated by ""fitask" -type=Route"; DO NOT EDIT

package awstasks

import (
	"encoding/json"

	"k8s.io/kube-deploy/upup/pkg/fi"
)

// Route

// JSON marshalling boilerplate
type realRoute Route

func (o *Route) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realRoute
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = Route(r)
	return nil
}

var _ fi.HasName = &Route{}

func (e *Route) GetName() *string {
	return e.Name
}

func (e *Route) SetName(name string) {
	e.Name = &name
}

func (e *Route) String() string {
	return fi.TaskAsString(e)
}
