// Code generated by ""fitask" -type=Keypair"; DO NOT EDIT

package fitasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// Keypair

// JSON marshalling boilerplate
type realKeypair Keypair

func (o *Keypair) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realKeypair
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = Keypair(r)
	return nil
}

var _ fi.HasName = &Keypair{}

func (e *Keypair) GetName() *string {
	return e.Name
}

func (e *Keypair) SetName(name string) {
	e.Name = &name
}

func (e *Keypair) String() string {
	return fi.TaskAsString(e)
}
