// Code generated by ""fitask" -type=Secret"; DO NOT EDIT

package fitasks

import (
	"encoding/json"

	"k8s.io/kube-deploy/upup/pkg/fi"
)

// Secret

// JSON marshalling boilerplate
type realSecret Secret

func (o *Secret) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realSecret
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = Secret(r)
	return nil
}

var _ fi.HasName = &Secret{}

func (e *Secret) GetName() *string {
	return e.Name
}

func (e *Secret) SetName(name string) {
	e.Name = &name
}

func (e *Secret) String() string {
	return fi.TaskAsString(e)
}
