// Code generated by ""fitask" -type=IPAddress"; DO NOT EDIT

package gcetasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// IPAddress

// JSON marshalling boilerplate
type realIPAddress IPAddress

// UnmarshalJSON implements conversion to JSON, supporitng an alternate specification of the object as a string
func (o *IPAddress) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realIPAddress
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = IPAddress(r)
	return nil
}

var _ fi.HasName = &IPAddress{}

// GetName returns the Name of the object, implementing fi.HasName
func (o *IPAddress) GetName() *string {
	return o.Name
}

// SetName sets the Name of the object, implementing fi.SetName
func (o *IPAddress) SetName(name string) {
	o.Name = &name
}

// String is the stringer function for the task, producing readable output using fi.TaskAsString
func (o *IPAddress) String() string {
	return fi.TaskAsString(o)
}
