// Code generated by ""fitask" -type=ManagedInstanceGroup"; DO NOT EDIT

package gcetasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// ManagedInstanceGroup

// JSON marshalling boilerplate
type realManagedInstanceGroup ManagedInstanceGroup

func (o *ManagedInstanceGroup) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realManagedInstanceGroup
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = ManagedInstanceGroup(r)
	return nil
}

var _ fi.HasName = &ManagedInstanceGroup{}

func (e *ManagedInstanceGroup) GetName() *string {
	return e.Name
}

func (e *ManagedInstanceGroup) SetName(name string) {
	e.Name = &name
}

func (e *ManagedInstanceGroup) String() string {
	return fi.TaskAsString(e)
}
