// Code generated by ""fitask" -type=PersistentDisk"; DO NOT EDIT

package gcetasks

import (
	"encoding/json"

	"k8s.io/kops/upup/pkg/fi"
)

// PersistentDisk

// JSON marshalling boilerplate
type realPersistentDisk PersistentDisk

func (o *PersistentDisk) UnmarshalJSON(data []byte) error {
	var jsonName string
	if err := json.Unmarshal(data, &jsonName); err == nil {
		o.Name = &jsonName
		return nil
	}

	var r realPersistentDisk
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	*o = PersistentDisk(r)
	return nil
}

var _ fi.HasName = &PersistentDisk{}

func (e *PersistentDisk) GetName() *string {
	return e.Name
}

func (e *PersistentDisk) SetName(name string) {
	e.Name = &name
}

func (e *PersistentDisk) String() string {
	return fi.TaskAsString(e)
}
