apiVersion: v1
kind: Secret
metadata:
  name: clusterapi-k8s-local-kubeconfig
  namespace: kube-system
  labels:
    cluster.x-k8s.io/cluster-name: clusterapi-k8s-local
type: Opaque
stringData:
  value: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://100.64.0.1
        tls-server-name: kubernetes.default
      name: clusterapi.k8s.local
    contexts:
    - context:
        cluster: clusterapi.k8s.local
        user: clusterapi.k8s.local
      name: clusterapi.k8s.local
    current-context: clusterapi.k8s.local
    users:
    - name: clusterapi.k8s.local
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-pod-reader
  namespace: capi-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # TODO: We only need to read pods
subjects:
- kind: ServiceAccount
  name: capi-manager
  namespace: capi-system
