# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import testdata_pb2 as testdata__pb2


class TestDataStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListTestJobs = channel.unary_stream(
        '/TestData/ListTestJobs',
        request_serializer=testdata__pb2.ListTestJobsRequest.SerializeToString,
        response_deserializer=testdata__pb2.TestJob.FromString,
        )
    self.ListTestJobRuns = channel.unary_stream(
        '/TestData/ListTestJobRuns',
        request_serializer=testdata__pb2.ListTestJobRunsRequest.SerializeToString,
        response_deserializer=testdata__pb2.TestJobRun.FromString,
        )
    self.GetTestJobRunResults = channel.unary_unary(
        '/TestData/GetTestJobRunResults',
        request_serializer=testdata__pb2.GetTestJobRunResultsRequest.SerializeToString,
        response_deserializer=testdata__pb2.TestJobRunResults.FromString,
        )


class TestDataServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListTestJobs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTestJobRuns(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTestJobRunResults(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestDataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListTestJobs': grpc.unary_stream_rpc_method_handler(
          servicer.ListTestJobs,
          request_deserializer=testdata__pb2.ListTestJobsRequest.FromString,
          response_serializer=testdata__pb2.TestJob.SerializeToString,
      ),
      'ListTestJobRuns': grpc.unary_stream_rpc_method_handler(
          servicer.ListTestJobRuns,
          request_deserializer=testdata__pb2.ListTestJobRunsRequest.FromString,
          response_serializer=testdata__pb2.TestJobRun.SerializeToString,
      ),
      'GetTestJobRunResults': grpc.unary_unary_rpc_method_handler(
          servicer.GetTestJobRunResults,
          request_deserializer=testdata__pb2.GetTestJobRunResultsRequest.FromString,
          response_serializer=testdata__pb2.TestJobRunResults.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TestData', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
