# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testdata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testdata.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0etestdata.proto\"7\n\x07TestJob\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\t\x12\x0e\n\x06prefix\x18\x03 \x01(\t\"P\n\nTestJobRun\x12\x10\n\x08job_name\x18\x01 \x01(\t\x12\x10\n\x08run_name\x18\x02 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x03 \x01(\t\x12\x0e\n\x06prefix\x18\x04 \x01(\t\"\x8d\x01\n\x11TestJobRunResults\x12\x10\n\x08job_name\x18\x01 \x01(\t\x12\x10\n\x08run_name\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x0e\n\x06passed\x18\x05 \x01(\x08\x12!\n\x08\x66\x65\x61tures\x18\x06 \x03(\x0b\x32\x0f.TestJobFeature\",\n\x0eTestJobFeature\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x15\n\x13ListTestJobsRequest\"/\n\x16ListTestJobRunsRequest\x12\x15\n\x03job\x18\x01 \x01(\x0b\x32\x08.TestJob\"7\n\x1bGetTestJobRunResultsRequest\x12\x18\n\x03run\x18\x01 \x01(\x0b\x32\x0b.TestJobRun2\xc7\x01\n\x08TestData\x12\x32\n\x0cListTestJobs\x12\x14.ListTestJobsRequest\x1a\x08.TestJob\"\x00\x30\x01\x12;\n\x0fListTestJobRuns\x12\x17.ListTestJobRunsRequest\x1a\x0b.TestJobRun\"\x00\x30\x01\x12J\n\x14GetTestJobRunResults\x12\x1c.GetTestJobRunResultsRequest\x1a\x12.TestJobRunResults\"\x00\x42\x0eZ\x0cpkg/testdatab\x06proto3')
)




_TESTJOB = _descriptor.Descriptor(
  name='TestJob',
  full_name='TestJob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TestJob.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bucket', full_name='TestJob.bucket', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='TestJob.prefix', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=73,
)


_TESTJOBRUN = _descriptor.Descriptor(
  name='TestJobRun',
  full_name='TestJobRun',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_name', full_name='TestJobRun.job_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_name', full_name='TestJobRun.run_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bucket', full_name='TestJobRun.bucket', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='TestJobRun.prefix', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=155,
)


_TESTJOBRUNRESULTS = _descriptor.Descriptor(
  name='TestJobRunResults',
  full_name='TestJobRunResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_name', full_name='TestJobRunResults.job_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_name', full_name='TestJobRunResults.run_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='TestJobRunResults.result', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TestJobRunResults.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passed', full_name='TestJobRunResults.passed', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='TestJobRunResults.features', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=299,
)


_TESTJOBFEATURE = _descriptor.Descriptor(
  name='TestJobFeature',
  full_name='TestJobFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TestJobFeature.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TestJobFeature.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=345,
)


_LISTTESTJOBSREQUEST = _descriptor.Descriptor(
  name='ListTestJobsRequest',
  full_name='ListTestJobsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=368,
)


_LISTTESTJOBRUNSREQUEST = _descriptor.Descriptor(
  name='ListTestJobRunsRequest',
  full_name='ListTestJobRunsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job', full_name='ListTestJobRunsRequest.job', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=417,
)


_GETTESTJOBRUNRESULTSREQUEST = _descriptor.Descriptor(
  name='GetTestJobRunResultsRequest',
  full_name='GetTestJobRunResultsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='run', full_name='GetTestJobRunResultsRequest.run', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=474,
)

_TESTJOBRUNRESULTS.fields_by_name['features'].message_type = _TESTJOBFEATURE
_LISTTESTJOBRUNSREQUEST.fields_by_name['job'].message_type = _TESTJOB
_GETTESTJOBRUNRESULTSREQUEST.fields_by_name['run'].message_type = _TESTJOBRUN
DESCRIPTOR.message_types_by_name['TestJob'] = _TESTJOB
DESCRIPTOR.message_types_by_name['TestJobRun'] = _TESTJOBRUN
DESCRIPTOR.message_types_by_name['TestJobRunResults'] = _TESTJOBRUNRESULTS
DESCRIPTOR.message_types_by_name['TestJobFeature'] = _TESTJOBFEATURE
DESCRIPTOR.message_types_by_name['ListTestJobsRequest'] = _LISTTESTJOBSREQUEST
DESCRIPTOR.message_types_by_name['ListTestJobRunsRequest'] = _LISTTESTJOBRUNSREQUEST
DESCRIPTOR.message_types_by_name['GetTestJobRunResultsRequest'] = _GETTESTJOBRUNRESULTSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestJob = _reflection.GeneratedProtocolMessageType('TestJob', (_message.Message,), dict(
  DESCRIPTOR = _TESTJOB,
  __module__ = 'testdata_pb2'
  # @@protoc_insertion_point(class_scope:TestJob)
  ))
_sym_db.RegisterMessage(TestJob)

TestJobRun = _reflection.GeneratedProtocolMessageType('TestJobRun', (_message.Message,), dict(
  DESCRIPTOR = _TESTJOBRUN,
  __module__ = 'testdata_pb2'
  # @@protoc_insertion_point(class_scope:TestJobRun)
  ))
_sym_db.RegisterMessage(TestJobRun)

TestJobRunResults = _reflection.GeneratedProtocolMessageType('TestJobRunResults', (_message.Message,), dict(
  DESCRIPTOR = _TESTJOBRUNRESULTS,
  __module__ = 'testdata_pb2'
  # @@protoc_insertion_point(class_scope:TestJobRunResults)
  ))
_sym_db.RegisterMessage(TestJobRunResults)

TestJobFeature = _reflection.GeneratedProtocolMessageType('TestJobFeature', (_message.Message,), dict(
  DESCRIPTOR = _TESTJOBFEATURE,
  __module__ = 'testdata_pb2'
  # @@protoc_insertion_point(class_scope:TestJobFeature)
  ))
_sym_db.RegisterMessage(TestJobFeature)

ListTestJobsRequest = _reflection.GeneratedProtocolMessageType('ListTestJobsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTTESTJOBSREQUEST,
  __module__ = 'testdata_pb2'
  # @@protoc_insertion_point(class_scope:ListTestJobsRequest)
  ))
_sym_db.RegisterMessage(ListTestJobsRequest)

ListTestJobRunsRequest = _reflection.GeneratedProtocolMessageType('ListTestJobRunsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTTESTJOBRUNSREQUEST,
  __module__ = 'testdata_pb2'
  # @@protoc_insertion_point(class_scope:ListTestJobRunsRequest)
  ))
_sym_db.RegisterMessage(ListTestJobRunsRequest)

GetTestJobRunResultsRequest = _reflection.GeneratedProtocolMessageType('GetTestJobRunResultsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTESTJOBRUNRESULTSREQUEST,
  __module__ = 'testdata_pb2'
  # @@protoc_insertion_point(class_scope:GetTestJobRunResultsRequest)
  ))
_sym_db.RegisterMessage(GetTestJobRunResultsRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\014pkg/testdata'))

_TESTDATA = _descriptor.ServiceDescriptor(
  name='TestData',
  full_name='TestData',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=477,
  serialized_end=676,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListTestJobs',
    full_name='TestData.ListTestJobs',
    index=0,
    containing_service=None,
    input_type=_LISTTESTJOBSREQUEST,
    output_type=_TESTJOB,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListTestJobRuns',
    full_name='TestData.ListTestJobRuns',
    index=1,
    containing_service=None,
    input_type=_LISTTESTJOBRUNSREQUEST,
    output_type=_TESTJOBRUN,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTestJobRunResults',
    full_name='TestData.GetTestJobRunResults',
    index=2,
    containing_service=None,
    input_type=_GETTESTJOBRUNRESULTSREQUEST,
    output_type=_TESTJOBRUNRESULTS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTDATA)

DESCRIPTOR.services_by_name['TestData'] = _TESTDATA

# @@protoc_insertion_point(module_scope)
