name: 'Review Dependencies'

on:
  pull_request:
    paths:
      - 'go.mod'

permissions:
  contents: read

jobs:
  dependency-review:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: 'Review Dependencies'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
