topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/name: '{{ template "coredns.name" . }}'
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    topologyKey: topology.kubernetes.io/zone
    maxSkew: 1
    whenUnsatisfiable: DoNotSchedule
  - labelSelector:
      matchLabels:
        app.kubernetes.io/name: '{{ template "coredns.name" . }}'
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    topologyKey: kubernetes.io/hostname
    maxSkew: 1
    whenUnsatisfiable: DoNotSchedule

autoscaler:
  enabled: true
